[workspace]
members = ["aces", "esp"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Tom Knapen"]
edition = "2021"

[workspace.dependencies]
thiserror = "1"
log = "0"

[profile.release]
opt-level = "s"

[profile.dev]
opt-level = "z"
debug = true
