[build]
target = "riscv32imc-esp-espidf"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"
rustflags = ["--cfg", "espidf_time64", "-C", "default-linker-libraries"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
CRATE_CC_NO_DEFAULTS="1" # see https://github.com/esp-rs/esp-idf-sys/issues/297
ESP_IDF_TOOLS_INSTALL_DIR = { value = "global" }
ESP_IDF_SDKCONFIG_DEFAULTS = { value = "sdkconfig.defaults", relative = true }
ESP_IDF_VERSION = "v5.1.2" # enables the esp-idf-sys "native" build feature (`cargo build --features native`) to build against ESP-IDF
ESP_IDF_SYS_ROOT_CRATE = "client-esp"
